// vagrant-up-all
// ver 1.0.2
// date: 2023-02-15

node("vagrant") {

    def u = env.VG_USER
    def h = ""
    def o = env.SSH_OPTIONS
    def home = env.VG_PATH
    
    stage('Init') {
        echo "--- ${JOB_NAME} ---"
        sh 'echo "JOB_START: $(date)"'

        echo "DEVOPS_USER: ${u}"
        echo "HOST: ${h}"

        h = env.VG_HOST

        sh "ssh -o ${o} ${u}@${h} hostnamectl; df -Th /; uptime; \
            last | grep '' -m3"

        envName = params.ENV_NAME
        echo "Parameter: ${envName}"
        sh "ssh -o ${o} ${u}@${h} 'cd ${home}; \
            vagrant status'"
    }

    stage('Up all VMs') {
        echo 'Up all VMs...'

        sh "ssh -o ${o} ${u}@${h} 'cd ${home}; \
            vagrant up'"
    }
}