// ansible-init-agent
// ver 1.0.6
// date: 2022-02-16

// Prerequisites:
// - Vagrant checks that the VM is running
// - first time start should be done from host with Absible (e.g. VG_HOST)
// - Ansible VM shoud be created and updated, use vagrant-update-system
//
// TO DO:
// - Remove key operations into Key Deployment Center

// It is supposed that Ansible will be installed on the Jenkins agent

node("ansible") {
    def u = env.VG_USER
    def devops = env.DEVOPS_USER
    def h = env.VG_HOST
    def o = env.SSH_OPTIONS
    def home = env.VG_PATH
    def devopsHome = env.DEVOPS_PROJECT_PATH
    def devopsProject = env.DEVOPS_PROJECT_NAME
    def envName = ""
    def agent = ""

    properties([
        parameters([
            choice(choices: ['terraform', 'jenkins', 'jagent1', 'gitlab', 'gitlab1', 'dev', 'qa', 'integ', 'prod', 'dev001'], 
            description: 'Select a VM to install Ansible and Git on the Jenkins agent.', name: 'ENV_NAME')
        ])
    ])
    
    stage('Init') {
        echo "--- ${JOB_NAME} ---"
        sh 'echo "JOB_START: $(date)"'

        echo "DEVOPS_USER: ${u}"
        echo "HOST: ${h}"
        echo "PATH: ${home}"

        // Prerequisites:
        // - first time start should be done from host with Absible (e.g. VG_HOST)
        
        echo "Host statistics:"
        sh "ssh -o ${o} ${u}@${h} 'hostnamectl; df -Th /; uptime; \
            last | grep \"\" -m3' \
        "

        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; \
            vagrant status ${envName}' \
        "
        
        envName = params.ENV_NAME        
        agent = params.ENV_NAME
        echo "Parameter: ${envName}"
        echo "agent: ${agent}"  
        u = env.DEVOPS_USER
        h = env.ANSIBLE_HOST    
        
        echo "Agent statistics:"
        sh "ssh -o ${o} ${u}@${h} 'hostnamectl; df -Th /; uptime; \
            last | grep \"\" -m3' \
        "    
    }

    stage('Configure network') {
        echo 'Configure network...'
        
        home = env.ANSIBLE_PATH
        echo "DEVOPS_USER: ${u}"
        echo "HOST: ${h}"
        echo "PATH: ${home}"
        
        home = env.ANSIBLE_PATH
        echo "ANSIBLE_PATH: ${home}"

        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook config_network.yml -e \"host_or_group=${envName}\"' \
        "
        echo 'network configured...'
    }

    stage('Add devops user') {
        echo 'Add devops user...'

        // TO DO:
        // - Remove key operations into Key Deployment Center

        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook create_devops_user.yml -e \"host_or_group=${envName}\" &>/dev/null; \
            [ \$? ] && echo \"user created...\"; \
            scp -o ${o} ~/.ssh/devops_id_rsa devops@${agent}:.ssh/id_rsa; \
            scp -o ${o} ~/.ssh/devops_id_rsa.pub devops@${agent}:~/.ssh/id_rsa.pub; \
            scp -o ${o} ~/.ssh/devops_id_rsa devops@${agent}:.ssh/; \
            scp -o ${o} ~/.ssh/devops_id_rsa.pub devops@${agent}:~/.ssh/; \
            [ \$? ] && echo \"keys copied...\"' \
        "
        echo 'devops user added...'
    }
    
    stage('Add jenkins user') {
        echo 'Add jenkins user...'

        // TO DO:
        // - Remove key operations into Key Deployment Center

        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook create_jenkins_user.yml -e \"host_or_group=${envName}\" &>/dev/null; \
            [ \$? ] && echo \"user created...\"; \
            scp -o ${o} ~/.ssh/devops_id_rsa jenkins@${agent}:.ssh/id_rsa; \
            scp -o ${o} ~/.ssh/devops_id_rsa.pub jenkins@${agent}:~/.ssh/id_rsa.pub; \
            [ \$? ] && echo \"keys copied...\"' \
        "
        echo 'jenkins user added...'
    }
    
    stage('Install Python') {
        echo 'Install Python...'

        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook deploy_python.yml -e \"host_or_group=${envName}\"' \
        "
        echo 'python installed...'
    }

    stage('Install Ansible') {
        echo 'Install Ansible...'
        
        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook deploy_ansible.yml -e \"host_or_group=${envName}\"' \
        "
        echo 'ansible installed...'
    }
    
    stage('Install Java 17') {
        echo 'Install Java 17...'
        
        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook deploy_java17_devel.yml -e \"host_or_group=${envName}\"' \
        "
        echo 'java 17 installed...'
    }

    stage('Install Git') {
        echo 'Install Git...'
        
        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            ansible-playbook deploy_git.yml -e \"host_or_group=${envName}\"; \
            ansible-playbook config_git.yml -e \"host_or_group=${envName}\"' \
        "
        echo 'git installed...'
        
        sh 'echo "JOB_FINISH: $(date)"'
    }

    stage('Clone Git') {
        echo 'Clone git...'
        
        sh "ssh -o ${o} ${u}@${envName} '[ ! -d ${u} ] && mkdir -p ${u} || echo Exist; \
            [ -d ${u} ] && cd ${u} || echo Absent; \
            [ ! -d ${devopsHome}/.git ] && ssh-keyscan github.com >> ~/.ssh/known_hosts || echo Exist; \
            [ ! -d ${devopsHome}/.git ] && git clone git@github.com:y-kolyada/${devopsProject}.git || echo Exist' \
        "
        echo 'devops project cloned...'
    }
    
    stage('Clone Inventory') {
        echo 'Clone Inventory...'
        
        u = env.VG_USER
        h = env.VG_HOST
        home = env.ANSIBLE_PATH
        
        sh "ssh -o ${o} ${u}@${h} 'cd ~/${home}; pwd; \
            scp -r ./inventory/* ${devops}@${envName}:~/${home}/inventory/' \
        "
        echo 'inventory cloned...'
    }
}