// cd-prod-aws
// ver 1.0.1
// date: 2023-02-22

// Prerequisites:
// - build-app-dev job
// - terraform-deploy-prodaws job

node {
    def u = env.DEVOPS
    def h = env.VG_HOST
    def o = env.SSH_OPTIONS
    def home = env.VG_PATH
    def envName = ""

    stage('Init') {
        echo "--- ${JOB_NAME} ---"
        sh 'echo "JOB_START: $(date)"'

        echo "DEVOPS_USER: ${u}"
        echo "HOST: ${h}"

        sh "hostnamectl; df -Th /; uptime; last | grep '' -m3"

        envName = "terraform"
        echo "Parameter: ${envName}"
        
        h = env.VG_HOST

        // sh 'ssh -o ${SSH_OPTIONS} ${VG_USER}@${VG_HOST} "hostnamectl"'
        //sh "ssh -o ${o} ${u}@${h} hostnamectl; df -Th /; uptime; \
        //    last | grep '' -m3"
        
        //sh "ssh -o ${o} ${u}@${h} 'cd ${home}; \
        //    vagrant status ${envName}'"
    }
    
    stage('CD on AWS PROD') {
        echo 'CD on AWS PROD...'
        
        build job:'terraform-deploy-prodaws', wait: true

        sh 'echo "JOB_FINISH: $(date)"'
    }
}