---
# Create COPR Infrastructure for the GitLab Playbooks
- name: Activate Firewall and SSH traffic Playbook
  ansible.builtin.import_playbook: activate_firewall.yml

- name: Create DevOps Users Playbook
  ansible.builtin.import_playbook: create_devops_user.yml

#- name: Create New Users Playbook
#  ansible.builtin.import_playbook: create_users.yml

- name: Add SSH Keys to hosts Playbook
  ansible.builtin.import_playbook: copy_keys.yml

- name: Deploy git Playbook
  ansible.builtin.import_playbook: deploy_git.yml