---
- name: Create "{{ user }}" dev user Playbook
  vars_files:
    - inventory/group_vars/infra
  vars:
    user: dev
    ansible_user: devops
  hosts: "{{ host_or_group }}"
  gather_facts: false
  become: true
  tasks:
    - name: Create dev user Task
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        password: "{{ default_devops_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        groups: "{{ admin_group }}"
        create_home: true
        comment: "User \"{{ user }}\" Admin Account"
        expires: -1
      loop: 
        - "{{ user }}"

    - name: Install SSH Authorized Key for "{{ user }}" user Task
      ansible.posix.authorized_key:        
        user: "{{ user }}"
        state: present
        manage_dir: true
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Resolve "[sss_cache] [sysdb_domain_cache_connect] (0x0010)" Error Task
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - /var/lib/sss/db/cache_implicit_files.ldb
