---
- name: Create DevOps Users Playbook
  vars_files:
    - inventory/group_vars/infra
    #- inventory/group_vars/development
  hosts: "{{ host_or_group }}"
  gather_facts: false
  become: true
  tasks:
    - name: Create DevOps Users Task
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        password: "{{ default_devops_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        groups: "{{ admin_group }}"
        create_home: true
        comment: 'Ansible "devops" Account'
        expires: -1
      loop: "{{ devops_users }}"

    - name: Install SSH Key for devop Users Task
      ansible.posix.authorized_key:        
        user: devops
        state: present
        manage_dir: true
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Setup DevOps Sudo Access
      ansible.builtin.copy:
        dest: /etc/sudoers.d/devops
        content: 'devops ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: Resolve "[sss_cache] [sysdb_domain_cache_connect] (0x0010)" Error Task
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - /var/lib/sss/db/cache_implicit_files.ldb
